### ISSUE TITLE
Infinite "loading packages" step

### ISSUE THREAD

**Issue by kyle-hiller-nh** [Tinder/bazel-diff#102]
Hello,

I can't manage to reproduce this locally because it is currently working on my machine, but in our CI/CD pipeline when I'm generating hashes, the command seems to get stuck while loading packages during one of the Bazel queries. 

`Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 504 packages loaded
    currently loading: 
Loading: 504 packages loaded
    currently loading: 
Loading: 504 packages loaded
    currently loading: 
Loading: 504 packages loaded
    currently loading: 
Loading: 504 packages loaded
    currently loading: 
Loading: 504 packages loaded
    currently loading: 
Loading: 504 packages loaded
    currently loading: 
Loading: 504 packages loaded
    currently loading: 
Loading: 504 packages loaded
    currently loading: 
Loading: 504 packages loaded
    currently loading: 
Loading: 504 packages loaded
    currently loading: 
Loading: 504 packages loaded
    currently loading: `

Eventually it will reach 505 but at that point it just sits at `Loading: 505 packages loaded` for an indeterminate amount of time (has gone 20+ minutes before)

Any idea why this might happen?

**Comment by tinder-maxwellelliott** [comment]
I believe this was fixed recently, can you try again?
