### ISSUE TITLE
why the check for ensureAllChangesAreCommitted

### ISSUE THREAD

**Issue by cristifalcas** [Tinder/bazel-diff#104]
Hi, what is the purpose of checking that all git changes are committed: https://github.com/Tinder/bazel-diff/blob/master/src/main/java/com/bazel_diff/main.java#L128-L136?

For example I usually have extra files in my git repo and because of this the diff fails.

I'm trying to understand if this an artificial limitation, or if it's necessary.

**Comment by tinder-maxwellelliott** [comment]
I think this logic can be removed, it was due to the initial implementation of bazel-diff

**Comment by tinder-maxwellelliott** [comment]
Logic has been removed

**Comment by cristifalcas** [comment]
Can you publish a new release, please?
