### ISSUE TITLE
Unable to run due to failed to download zlib 1.2.11.tar.gz

### ISSUE THREAD

**Issue by fa93hws** [Tinder/bazel-diff#106]
> openjdk version "11.0.5" 2019-10-15 LTS
> OpenJDK Runtime Environment Zulu11.35+15-CA (build 11.0.5+10-LTS)
> OpenJDK 64-Bit Server VM Zulu11.35+15-CA (build 11.0.5+10-LTS, mixed mode)

When running `bazel build //:bazel-diff` I got
> WARNING: Download from https://zlib.net/zlib-1.2.11.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
> ERROR: An error occurred during the fetch of repository 'zlib':

I've a check it seems there is only https://zlib.net/zlib-1.2.12.tar.gz now and there is no 1.2.11

**Comment by tinder-maxwellelliott** [comment]
Hello there,

Are you able to build off of this PR https://github.com/Tinder/bazel-diff/pull/105

**Comment by fa93hws** [comment]
Ah yea that works fine in https://github.com/Tinder/bazel-diff/pull/105.

**Comment by tinder-maxwellelliott** [comment]
I will merge this soon!

**Comment by tinder-maxwellelliott** [comment]
Resolved on master
