### ISSUE TITLE
Filter targets

### ISSUE THREAD

**Issue by bazaglia** [Tinder/bazel-diff#135]
I see the `avoid_query` functionality (#26, #28) that allows targets to not be included in the set of targets generated by bazel-diff doesn't exist in the latest release.

I have a use case that I believe to be very usual: I'm specifying the targets that bazel-diff generates to `bazel test` and I don't want Docker-related targets to be built since it's gonna take way too much time.

**Comment by tinder-maxwellelliott** [comment]
Hello @bazaglia,

Can't you take the resulting targets and then perform another query to figure out the final desired set? This is exactly what we do internally
