### ISSUE TITLE
Add support for bazel query output formats for the get-impacted-targets command output

### ISSUE THREAD

**Issue by mjduijn** [Tinder/bazel-diff#143]
In our setup we enable specific CI pipelines depending on the types of targets that were changed. To get this kind of metadata from the output of `bazel-diff get-impacted-targets`, we need to run another set of bazel queries because the list of targets may be too large for a single bazel query. Splitting up one large bazel query into multiple smaller ones is one of the USPs for bazel-diff, and so I was hoping to add the functionality here. 

The functionality could come as part of an output format for `get-impacted-targets`, another option would be to add a new subcommand that transforms the current output into a standard bazel query output (streamed_proto/xml/..).

What do you think?

**Comment by tinder-maxwellelliott** [comment]
@mjduijn Thanks for the ticket!

Can't you simply save the output of bazel diff to a file and propagate that through different pipelines? Then you can read that file, mutate a copy of it for the query you need and then use -[-query_file](https://docs.bazel.build/versions/main/command-line-reference.html#flag--query_file)

**Comment by mjduijn** [comment]
Ha err yeah that works, thanks! I wasn't aware of the argument.
