### ISSUE TITLE
How to consume Impacted_targets.txt 

### ISSUE THREAD

**Issue by sanju-naik** [Tinder/bazel-diff#151]
Hi,

I tried running bazel-diff on a sample project using below command 
```
./bazel-diff-example.sh //path-to-sample-repo bazelisk commit-hash-A commit-hash-B
```

The output it produces at the end i.e ` /tmp/impacted_targets.txt` contains things such as Info.plist file, .ipa , .swift files etc. I was expecting that this would give me a list of Bazel targets which I can build & test, seems like that's not the case. 

Any examples on How to process and extract targets from `impacted_targets.txt` and then run `bazel test` on those targets

Thanks In advance!

**Comment by tinder-maxwellelliott** [comment]
Hello there,

I would use [this flag](https://bazel.build/reference/command-line-reference#flag--query_file) and the `bazel query` command to construct a query from the results you receive, you can filter on the impacted list for only the kinds of targets you want. There is no way I can guess at what targets each user is interested in and it is simple enough to construct the query.

**Comment by sanju-naik** [comment]
Hi @tinder-maxwellelliott I played around `bazel query` and tried this approach 
```
bazel query --query_file=/tmp/impacted_tagets.txt
```
but couldn't get what I want from that file, it basically outputs the same entire contents of the file. 

When we are running `bazel query` with this [flag,](https://bazel.build/reference/command-line-reference#flag--query_file) We can't pass the query as well from the terminal as it would allow either of them so the remaining options are `output` parameter and [filter](https://docs.bazel.build/versions/main/query.html#filter), but no luck with these as well.

Can you help with an example query? Say this is my output (impacted_targets.txt) 
```
//foo/test.swift
//foo:bar.ipa
//foo:bar
```
And I want to extract only `//foo:bar` from the output, as that's the affected target I want to build and test, Any idea on how to write a query for this? 

TIA!
