### ISSUE TITLE
Changes to workspace_status don't change bazel-diff output hashes

### ISSUE THREAD

**Issue by dgnemo** [Tinder/bazel-diff#165]
Changes in workspace_status don't change bazel-diff output hashes for the targets that depend on `ctx.info_file` (the file containing the current workspace_status)

an example of these rules are:

* rules_docker: container push https://github.com/bazelbuild/rules_docker/blob/master/docs/container.md#container_push
* helm_chart: https://github.com/masmovil/bazel-rules/blob/master/helm/helm-chart-package.bzl#L32

I can create an example project to reproduce this, but I wanted to open the issue first in case the behavior is expected / known.

note that `ctx.info_file` is not listed in the rules attributes, but is used by the rule implementation function (it's passed as additional input to `ctx.actions.run(inputs = ....`

**Comment by tinder-maxwellelliott** [comment]
I would use `-s=<seedFilepaths>` and place this file in the list. Whenever that file changes it would invalidate the graph.
