### ISSUE TITLE
`bazel-diff` does not handle configurable build attributes

### ISSUE THREAD

**Issue by ZhihaoGong** [Tinder/bazel-diff#170]
Currently, `bazel diff` does not handle configurable build attributes. The output is not correct if `select` and `target_compat_with` is in `BUILD` file

**Comment by tinder-maxwellelliott** [comment]
This is expected as this tool does not use `cquery` for performance reasons. There are other target selection algorithms that do use `query` but there is a significant performance overhead versus `query`.
