### ISSUE TITLE
Support consuming bazel-diff without bzlmod

### ISSUE THREAD

**Issue by joeljeske** [Tinder/bazel-diff#209]
After https://github.com/Tinder/bazel-diff/commit/27adb8df46083f360d967428658a826bba1ea920, consumers using bazel-diff from source via WORKSPACE are unable to load artifacts.bzl, or repository.bzl. During the community transition to bzlmod, you should support both strategies of consumption. 

Please re-add repository.bzl and artifacts.bzl with equivalent contents of MODULE.bazel

**Comment by tinder-maxwellelliott** [comment]
I am sorry for the inconvenience and I will work on fixing this soon. For now you can use a JAR directly to unblock yourself while I complete the needed work.
