### ISSUE TITLE
bazel-diff breaks with --noenable_workspace

### ISSUE THREAD

**Issue by fweikert** [Tinder/bazel-diff#236]
The external package no longer exists when --noenable_workspace is specified, thus breaking bazel-diff:

https://buildkite.com/bazel/bazel-bazel-github-presubmit/builds/23693#annotation-'diff_failed'

I expect many more users to run into this problem in the near future since --noenable_workspace will be the default in Bazel 8 (ETA EOY 2024), and with Bazel 9 any WORKSPACE functionality will cease to exist.

**Comment by maxwellE** [comment]
I can look into this next after I get the tool on the BCR

**Comment by honnix** [comment]
I think this shouldn't be hard to fix. It is a matter of optionally adding https://github.com/Tinder/bazel-diff/blob/32c728850200bbb3fbf0664d675ae9c05a69e800/cli/src/main/kotlin/com/bazel_diff/bazel/BazelClient.kt#L16, if I understood correctly.

**Comment by meteorcloudy** [comment]
Yes, `//external` no longer exists after disabling WORKSPACE.
