### ISSUE TITLE
Filter Targets tagged as "manual"

### ISSUE THREAD

**Issue by JorgeGarciaIrazabal** [Tinder/bazel-diff#26]
when running the example `bazel-diff-example.sh` on my repository, I also get the targets tagged as `manual`.

Bazel filters them when using wildcard target patters already ([link](https://docs.bazel.build/versions/master/guide.html)) and it would be great to have a configuration so we can filter them automatically with bazel-diff too.

BTW. This tool is great, thank you for open sourcing it 😄

**Comment by tinder-maxwellelliott** [comment]
@JorgeGarciaIrazabal Thanks for reaching out 😄 ! Glad you enjoy the tool. 

What kind of API would you expect to filter out these `manual` targets? Would you pass an additional flag to filter out these targets?

**Comment by JorgeGarciaIrazabal** [comment]
thank you for replying that fast!

So, in the command `bazel-diff generate-hashes`, maybe adding a `except_manual` flag to make it simple, or adding a `query_except` parameter where users can add more generic filters (for this example: `attr('tags', 'manual', //...)"`). 

I would vote for the `query_except` parameter, but I can see users preferring the simplicity of just a flag

Thank you again!

**Comment by tinder-maxwellelliott** [comment]
> thank you for replying that fast!
> 
> So, in the command `bazel-diff`, maybe adding a `except_manual` flag to make it simple, or adding a `query_except` parameter where users can add more generic filters (for this example: `attr('tags', 'manual', //...)"`).
> 
> I would vote for the `query_except` parameter, but I can see users preferring the simplicity of just a flag
> 
> Thank you again!

I think there could be value in adding a String parameter called `avoid_query`, targets that pass that query are excluded

**Comment by JorgeGarciaIrazabal** [comment]
> > thank you for replying that fast!
> > So, in the command `bazel-diff`, maybe adding a `except_manual` flag to make it simple, or adding a `query_except` parameter where users can add more generic filters (for this example: `attr('tags', 'manual', //...)"`).
> > I would vote for the `query_except` parameter, but I can see users preferring the simplicity of just a flag
> > Thank you again!
> 
> I think there could be value in adding a String parameter called `avoid_query`, targets that pass that query are excluded

yeah, that sounds good
