### ISSUE TITLE
Performance issues for large diffs

### ISSUE THREAD

**Issue by arc0** [Tinder/bazel-diff#27]
In our repo, we have 1000s of generated json files that are not tracked by bazel.

On diffs with ~1000 untracked files we're finding some performance problems stemming from the non-bazel query fix: https://github.com/Tinder/bazel-diff/pull/9.

Moving the partition to 100 improves the performance, but of course the original #8 bug occurs in this situation.

Any thoughts on how to keep the large partition size but still fix the query bug?

**Comment by tinder-maxwellelliott** [comment]
Hello @arc0 👋🏻 

It seems that Bazel query does return results with a warning when using the `--keep-going` flag, yet Java's `Process` type does not like that this command exits without a success code. I believe we could still capture the output from this command though, even when it fails.

I think that we can fix this by potentially wrapping our query for source files in another shell script that suppresses the failure exit code.

**Comment by arc0** [comment]
Nice! Thanks @tinder-maxwellelliott - that sounds good. I was also thinking about querying the other way, searching with `kind("source files", ... ` to get the list of tracked files, then filter the files going into the `rdeps` search. Could prevent a lot of unnecessary searches. I've got a draft working on a branch here https://github.com/arc0/bazel-diff/tree/diff-performance. Bit messy converting to real paths though. I wonder if there's a cleaner way to get the tracked file paths?

**Comment by thundergolfer** [comment]
So given we saw 45-1hr runtime (`2923.08s` last time I ran it) on the case with ~1000 untracked JSON files, what's the performance improvement when using https://github.com/arc0/bazel-diff/tree/diff-performance?

**Comment by tinder-maxwellelliott** [comment]
I will work on trying to get the `--keep-going` approach working and see how that performs with 1000 untracked files. Its a bummer Bazel makes this so hard to do
