### ISSUE TITLE
Potential bug in hash function

### ISSUE THREAD

**Issue by georgeBacon23** [Tinder/bazel-diff#34]
In the file TargetHashingClient.java, the function createHashForRule creates a hash for a rule by considering the rule's inputs and if necessary recursively hashing inputs that are rules. A hashmap ruleHashes is used to cache previously computed rule hashes. I think there is a bug here, as at least on my system, the MessageDigest object is reset when .digest() is called. So if the rule is in the cache, the first time it is found it will be reset when digest is called to update the parent's digest. Any other rules that use it will subsequently update with the wrong hash.

Am I missing something here?

**Comment by tinder-maxwellelliott** [comment]
@georgeBacon23 Thanks for reaching out. Do you have a demo project I can test this with? I have not seen this behavior myself.

 Is this the line in question? https://github.com/Tinder/bazel-diff/blob/0f9f17db25446634bb60e8be2c6e644be0b759c9/src/main/java/com/bazel_diff/TargetHashingClient.java#L115? We are simply using `ruleHashes` to avoid recomputing rule hashes that have already been computed, as you can see on https://github.com/Tinder/bazel-diff/blob/0f9f17db25446634bb60e8be2c6e644be0b759c9/src/main/java/com/bazel_diff/TargetHashingClient.java#L99

**Comment by georgeBacon23** [comment]
Hi, yes I believe when the method digest() is called on the MessageDigest object, the underlying bytes are reset. So next time it's retrieved you'll get a different result.

![image](https://user-images.githubusercontent.com/67277353/102253131-dd478800-3efe-11eb-9eb1-1cb47cb11711.png)

Sorry I don't have a project to hand that I can share. But I imagine any project with multiple targets which reference the same rule would show the issue. If you print the retrieved digest for the rule each time, it should have one value on the first call, then will be set to another for all subsequent calls. 

The problem can be avoided if instead of caching the MessageDigest object you store a copy of the byte array, so something like:

ruleHashes.put(rule.getName(), digest.digest().clone())

Obviously you'd have to update method signatures.

**Comment by georgeBacon23** [comment]
I saw it by making a modification like below, where TEST_TARGET is one to look out for and bytesDigestToString is a helper function for printing the digest:

```java

if (ruleInputDigest != null) {
    byte[] d = ruleInputDigest.digest();
    String name = inputRule.getName();
    if (name.equals("TEST_TARGET")){
        System.out.println("target, digest: " + name + " "+ bytesDigestToString(d)");
    }
    digest.update(d);
}

```

Also you might see that a lot of targets have the same final hash.

**Comment by tinder-maxwellelliott** [comment]
I have reproduced this issue locally, getting a fix up now
