### ISSUE TITLE
Logging switch for bazel calls and main

### ISSUE THREAD

**Issue by arc0** [Tinder/bazel-diff#36]
Our Bazel workspace does a lot of container pre-fetching and other setup tasks. As `bazel-diff` runs silently it is difficult to determine what Bazel is currently running, particularly on large diffs or critical changes.

This is a feature request for a `--verbose` switch that can re-enable Bazel logging for the queries, and just general logging around the stages of `bazel-diff`. Happy to assist!

**Comment by tinder-maxwellelliott** [comment]
Hello @arc0. 

I can easily add the ability to output any running Bazel queries to stdout, enabled with a `--verbose` flag. Let's start this this for now and see what else is required for debugging
