### ISSUE TITLE
Unknown option: '-t'

### ISSUE THREAD

**Issue by BalestraPatrick** [Tinder/bazel-diff#40]
Hello! 

I'm trying out version 2.0.2 (update: happening also on 2.1.0) but running the provided `bazel-diff-example.sh` causes an error when running the command `$bazel_path run //tools:bazel_diff -- -sh $starting_hashes_json -fh $final_hashes_json -w $workspace_path -b $bazel_path -o $impacted_test_targets_path -t` in our repo.

The errors is a follows:
```
Unknown option: '-t'
Usage: bazel-diff [-hV] [-aq=<avoidQuery>] -b=<bazelPath>
                  [-co=<bazelCommandOptions>] [-fh=<finalHashesJSONPath>]
                  [-o=<outputPath>] [-sh=<startingHashesJSONPath>]
                  [-so=<bazelStartupOptions>] -w=<workspacePath> [COMMAND]
Writes to a file the impacted targets between two Bazel graph JSON files
      -aq, --avoid-query=<avoidQuery>
                  A Bazel query string, any targets that pass this query will
                    be removed from the returned set of targets
  -b, --bazelPath=<bazelPath>
                  Path to Bazel binary
      -co, --bazelCommandOptions=<bazelCommandOptions>
                  Additional space separated Bazel command options used when
                    invoking Bazel
      -fh, --finalHashes=<finalHashesJSONPath>
                  The path to the JSON file of target hashes for the final
                    revision. Run 'generate-hashes' to get this value.
  -h, --help      Show this help message and exit.
  -o, --output=<outputPath>
                  Filepath to write the impacted Bazel targets to, newline
                    separated
      -sh, --startingHashes=<startingHashesJSONPath>
                  The path to the JSON file of target hashes for the initial
                    revision. Run 'generate-hashes' to get this value.
      -so, --bazelStartupOptions=<bazelStartupOptions>
                  Additional space separated Bazel client startup options used
                    when invoking Bazel
  -V, --version   Print version information and exit.
  -w, --workspacePath=<workspacePath>
                  Path to Bazel workspace directory.
Commands:
  generate-hashes     Writes to a file the SHA256 hashes for each Bazel Target
                        in the provided workspace.
  modified-filepaths  Writes to the file the modified filepaths between two
                        revisions.
```

All other commands work just fine, but the `-t` is unrecognized for some reason. Have you ever seen this before?

**Comment by BalestraPatrick** [comment]
Looks like the `-t` option was removed here: https://github.com/Tinder/bazel-diff/commit/e736e3fea2637a7e9d01b6416dd3f0b4fa01b379#diff-d4f1ce5d47a8030ce411c3c38c06b5b26a2b04c5ca919116318148a428dc97e6L144-L145

**Comment by tinder-maxwellelliott** [comment]
Hello @BalestraPatrick, yes the `-t` flag was removed in favor of the `--avoid-query` flag. You can emulate `-t` behavior by passing `--avoid-query "//... except tests(//...)"`

**Comment by jonahgeorge** [comment]
@tinder-maxwellelliott I may be misunderstanding the intended usage but the following patch is not working for me. The impacted targets list is correct; however, the impacted test targets is empty. Running `bazel query tests(//...)` works within my project and version 1.2.1 of Bazel-diff also returns the correct results. Would you mind taking a look when you have time?
```patch
diff --git a/bazel-diff-example.sh b/bazel-diff-example.sh
index 35ca927..0b981a7 100755
--- a/bazel-diff-example.sh
+++ b/bazel-diff-example.sh
@@ -37,7 +37,7 @@ echo "Determining Impacted Targets"
 $bazel_path run :bazel-diff -- -sh $starting_hashes_json -fh $final_hashes_json -w $workspace_path -b $bazel_path -o $impacted_targets_path
 
 echo "Determining Impacted Test Targets"
-$bazel_path run :bazel-diff -- -sh $starting_hashes_json -fh $final_hashes_json -w $workspace_path -b $bazel_path -o $impacted_test_targets_path -t
+$bazel_path run :bazel-diff -- -sh $starting_hashes_json -fh $final_hashes_json -w $workspace_path -b $bazel_path -o $impacted_test_targets_path --avoid-query "//... except tests(//...)"
 
 IFS=$'\n' read -d '' -r -a impacted_targets < $impacted_targets_path
 formatted_impacted_targets=$(IFS=$'\n'; echo "${impacted_targets[*]}")
```

**Comment by tinder-maxwellelliott** [comment]
> @tinder-maxwellelliott I may be misunderstanding the intended usage but the following patch is not working for me when applied to master. The impacted targets list is correct; however, the impacted test targets is empty. Running `bazel query 'tests(//...)'` works within my project and version 1.2.1 of Bazel-diff also returns the correct results. Would you mind taking a look when you have time?
> 
> ```diff
> diff --git a/bazel-diff-example.sh b/bazel-diff-example.sh
> index 35ca927..0b981a7 100755
> --- a/bazel-diff-example.sh
> +++ b/bazel-diff-example.sh
> @@ -37,7 +37,7 @@ echo "Determining Impacted Targets"
>  $bazel_path run :bazel-diff -- -sh $starting_hashes_json -fh $final_hashes_json -w $workspace_path -b $bazel_path -o $impacted_targets_path
>  
>  echo "Determining Impacted Test Targets"
> -$bazel_path run :bazel-diff -- -sh $starting_hashes_json -fh $final_hashes_json -w $workspace_path -b $bazel_path -o $impacted_test_targets_path -t
> +$bazel_path run :bazel-diff -- -sh $starting_hashes_json -fh $final_hashes_json -w $workspace_path -b $bazel_path -o $impacted_test_targets_path --avoid-query "//... except tests(//...)"
>  
>  IFS=$'\n' read -d '' -r -a impacted_targets < $impacted_targets_path
>  formatted_impacted_targets=$(IFS=$'\n'; echo "${impacted_targets[*]}")
> ```

Fixed in https://github.com/Tinder/bazel-diff/releases/tag/2.1.1
