### ISSUE TITLE
Infinite loop during bazel-diff

### ISSUE THREAD

**Issue by sjoerdvisscher** [Tinder/bazel-diff#45]
Sorry for this rather useless issue, but maybe it is just enough info to fix the bug. Otherwise feel free to close it.

I hit an infinite loop in bazel-diff, but only on CI, I could not reproduce this locally, hence the minimal information.
CI hanged during this step: `bazel run @bazel_diff//:bazel-diff -- -sh "$starting_hashes_json" -fh "$final_hashes_json" -w "$workspace_path" -b "$bazel_path" -o "$impacted_targets_path"`. 

I was able to work around it by running `bazel build ...` on CI first. The only difference I see between this build and other CI builds that did succeed is that in this case a relatively big external dependency was added. Maybe the issue arrises when it takes a few minutes before a bazel query returns its first result?

**Comment by tinder-maxwellelliott** [comment]
Hello @sjoerdvisscher,

Can you run your command again but pass the `--config=verbose` flag and share what output you can here. 

This is the line you need to modify in the example script to get this to work https://github.com/Tinder/bazel-diff/blob/master/bazel-diff-example.sh#L21

**Comment by sjoerdvisscher** [comment]
Sadly the PR with the issue has been merged after adding the workaround and I was not able to reproduce this by recreating the same PR.

**Comment by tinder-maxwellelliott** [comment]
Should we close this for now and reopen if you are able to use the `--config=verbose` flag when it happens again?

**Comment by sjoerdvisscher** [comment]
Will do. 👍
