### ISSUE TITLE
Not all changes detected

### ISSUE THREAD

**Issue by purkhusid** [Tinder/bazel-diff#46]
I've got the following BUILD.bazel file

```
load("@io_bazel_rules_docker//container:container.bzl", "container_image")
load("@io_bazel_rules_docker//docker/util:run.bzl", "container_run_and_commit_layer")
load("@io_bazel_rules_docker//docker/package_managers:download_pkgs.bzl", "download_pkgs")
load("@io_bazel_rules_docker//docker/package_managers:install_pkgs.bzl", "install_pkgs")

# Base docker image for our Scala services
download_pkgs(
    name = "base_packages",
    image_tar = "@openjdk_11_slim//image",
    packages = [
        "wget",
    ],
)

install_pkgs(
    name = "install_base_packages",
    image_tar = "@openjdk_11_slim//image",
    installables_tar = ":base_packages.tar",
    installation_cleanup_commands = "rm -rf /var/lib/apt/lists/*",
    output_image_name = "install_base_packages",
)

container_run_and_commit_layer(
    name = "base_run_commands",
    commands = [
        "wget -O /bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.3.6/grpc_health_probe-linux-amd64",
        "chmod +x /bin/grpc_health_probe",
    ],
    image = "install_base_packages.tar",
)

container_image(
    name = "scala_base_image",
    base = "@openjdk_11_slim//image",
    layers = ["base_run_commands"],
    # This is needed because the scala_image expectes the java executable
    # to be available at /usr/bin/java. We then use this image as a base
    # for the app image
    symlinks = {
        "/usr/bin/java": "/usr/local/openjdk-11/bin/java",
    },
    visibility = ["//visibility:public"],
)
```
If e.g. change the `download_pkgs` target to download `curl` as well then bazel-diff will not detect the changed targets.

**Comment by purkhusid** [comment]
I don't have a small repro at the moment but the snippet above should be enough to reproduce. You just have to have rules_docker and 
```
container_pull(
    name = "openjdk_11_slim",
    digest = "sha256:28b59dc9a129c75349418e3b75508fd8eef3b33dd7d796079d1d19445d907776",
    registry = "index.docker.io",
    repository = "library/openjdk",
)
```
In your WORKSPACE file

**Comment by tinder-maxwellelliott** [comment]
@purkhusid Thank you so much for reporting this. I will investigate this issue and update our integration tests to encompass this issue

**Comment by tinder-maxwellelliott** [comment]
@purkhusid Does https://github.com/Tinder/bazel-diff/pull/50 represent your situation correctly? It seems like `//:base_packages` is being picked up correctly

**Comment by purkhusid** [comment]
@tinder-maxwellelliott I tested this out again on our repo and it was always returning no impacted targets. I then tried it again with the latest master and that seems to work. But the funny thing is that is seems like it's the `bazel-diff-example.sh` script that is making the difference. 

If I copy the script from master to the release I'm using (2.1.2) then it also works...

**Comment by purkhusid** [comment]
As far as I can tell the only change is the the --script_path change

**Comment by purkhusid** [comment]
I'm trying to see if there might be some hidden errors that bazel-diff is masking. I think it might be worthwhile to output stderr for all the processes that bazel-diff starts

**Comment by tinder-maxwellelliott** [comment]
> As far as I can tell the only change is the the --script_path change

I also fixed another bug with spaces in rdeps queries https://github.com/Tinder/bazel-diff/pull/48

**Comment by tinder-maxwellelliott** [comment]
> I'm trying to see if there might be some hidden errors that bazel-diff is masking. I think it might be worthwhile to output stderr for all the processes that bazel-diff starts

If you pass `--config=verbose` to your Bazel invocation of `bazel-diff` you will get debug output

**Comment by purkhusid** [comment]
> > As far as I can tell the only change is the the --script_path change
> 
> I also fixed another bug with spaces in rdeps queries #48

Yeah, but I tried it with the script on master with Bazel diff v2.1.2 and that worked. I'll try creating a self contained repro tomorrow

**Comment by purkhusid** [comment]
@tinder-maxwellelliott I tried doing a minimal reproduction but I'm having a hard time doing so. There might be something in my repo that is making this fail. I can't share the code so I'll see if I can figure this out.

**Comment by tinder-maxwellelliott** [comment]
Thank you @purkhusid . Were you able to get output by adding the `--config=verbose` option?
