### ISSUE TITLE
bazelrc change is not reflected in bazel-diff

### ISSUE THREAD

**Issue by ThomasCJY** [Tinder/bazel-diff#58]
If I change build options (such as how dexing works in android) in my bazelrc file, all affected targets should be rebuild. However, currently, bazel-diff cannot detect this change.

I'm thinking we should add an skip-list which matches the name pattern of changed files and if matches then we'll return all targets.

**Comment by tinder-maxwellelliott** [comment]
Hello @ThomasCJY and thanks for reporting this. I will work on recreating this locally and add it to our integration tests

**Comment by tinder-maxwellelliott** [comment]
@ThomasCJY Getting more time to look at this now. Are you imagining we pass a regex into `generate-hashes` and if any of the modified filepaths match that regex then all targets need to be marked as changed?

**Comment by ThomasCJY** [comment]
I was thinking put all the regex in a file and pass the filename to `generate-hashes`. This option should be used together with `-m, --modifiedFilepaths=<modifiedFilepaths>`

**Comment by tinder-maxwellelliott** [comment]
@ThomasCJY the more I think about this, why can't we just traverse and read all the bazelrc files? We can SHA the contents of each and then SHA that value with the value from any imported bazelrc files

**Comment by tinder-maxwellelliott** [comment]
I think its best to simply go back to what you originally suggested and simply accept an array of file path regexes that will be checksummed and included in each files checksum. Reading the bazelrc files is hard to maintain and has edge cases
