### ISSUE TITLE
Error uncommitted changes but git showing no changes

### ISSUE THREAD

**Issue by hrvolapeter** [Tinder/bazel-diff#59]
After following the setup guide and adding bazel diff to BUILD file and running `bazel run //:bazel-diff --  modified-filepaths -w . -b $(which bazel)  "HEAD^" HEAD a ` exits with `There are active changes in '.', please commit these changes before running modified-filepaths`, however when running `git status --porcelain` immediately after the error in the same dir the output doesn't show any non-whitespace characters.

I'm running on MacOS

WORKSPACE
```
http_jar(
    name = "bazel_diff",
    urls = [
        "https://github.com/Tinder/bazel-diff/releases/download/2.1.2/bazel-diff_deploy.jar",
    ],
    sha256 = "a01d8e26dc0abfacd282f44a72434613d9799270bff406848e0ba8df7bae2081"
)
````

BUILD
```
java_binary(
    name = "bazel-diff",
    main_class = "com.bazel_diff.BazelDiff",
    runtime_deps = ["@bazel_diff//jar"],
)
```

**Comment by tinder-maxwellelliott** [comment]
Hello @hrvolapeter. This issue seems hard to diagnose remotely, do you mind making a small demo repo for me to work with?

**Comment by hrvolapeter** [comment]
Hi @tinder-maxwellelliott, thanks for checking the issue. However it seems like I cannot reproduce the problem anymore. However I think the problem might have been caused by running bazel diff from the workspace it was checking
