### ISSUE TITLE
Adding dependency to WORKSPACE interpreted as changing almost all targets

### ISSUE THREAD

**Issue by mikberg** [Tinder/bazel-diff#70]
Hi!

After upgrading from 2.3.0 to 2.4.0, we encountered an issue where a change to `WORKSPACE` resulted in almost all targets being marked as changed. The change only added a new dependency.

I'm not sure how this could have been introduced by the change set.

Let me know if there are more details I can provide.

**Comment by tinder-maxwellelliott** [comment]
Hello @mikberg, thanks for reporting the issue. If you have time could you put together a small repo that repros the issue? That really helps me because I can use it in an integration test after the fix is made

**Comment by mikberg** [comment]
I'll try to reproduce the issue in a shareable repo when I have time :+1:

**Comment by tinder-maxwellelliott** [comment]
> I'll try to reproduce the issue in a shareable repo when I have time 👍

Thank you!

**Comment by tinder-maxwellelliott** [comment]
@mikberg we haven't see anything on our end that looks like this issue. Unless you can provide an example repo can we close this for now?

**Comment by mikberg** [comment]
> @mikberg we haven't see anything on our end that looks like this issue. Unless you can provide an example repo can we close this for now?

Sorry, I won't be able to work on this for some time. Feel free to close this issue.
