### ISSUE TITLE
Hash all targets has poor performance with rules_pip

### ISSUE THREAD

**Issue by KevinJiao** [Tinder/bazel-diff#86]
Hi!

When upgrading to `3.0.0`, I'm seeing large performance regressions in "hash all targets" query with my targets that depend on a `rules_pip` generated external dependency. The key appears to be in the `kind('source file',  deps(//...))` query, which is not restricted to internal targets, and therefore will result in downloading every single external dependency and attempting to hash all the source files for external dependencies.

Pre upgrade, changes in external dependencies would be picked up by the hash implementation in `BazelRule.java`, without needing to actually download anything. For reference, this is the change in question: https://github.com/Tinder/bazel-diff/pull/72

I have a example repository in https://github.com/KevinJiao/pip-diff-repro, and some timings:
```
$ bazel version
Build label: 3.7.1
$ cd bazel-diff
$ git checkout 2.4.0
$ bazel build :bazel-diff
$ time bazel run :bazel-diff --config=verbose -- generate-hashes -b /usr/bin/bazel -w /home/kjiao/projects/pip-diff-repro /tmp/hash
hes_fast
INFO: Build completed successfully, 2 total actions
Executing Query: '//external:all-targets' + '//...:all-targets'

real    0m5.610s
user    0m0.748s
sys     0m0.160s

$ git checkout master
$ bazel build :bazel-diff
$ sudo rm -rf /data/home/kjiao/.cache/bazel/_bazel_kjiao/35b52e3c66a2af30496de6e275263eab
$ time bazel run :bazel-diff --config=verbose -- generate-hashes -b /usr/bin/bazel -w /home/kjiao/projects/pip-diff-repro /tmp/hash
INFO: Build completed successfully, 2 total actions
Executing Query: kind('source file', deps(//...))
Executing Query: '//external:all-targets' + '//...:all-targets'

real    0m24.143s
user    0m1.125s
sys     0m0.175s
```

24 seconds may not seem like a lot but the actual repo I'm working with has a few hundred pip dependencies and it isn't performant to have to download all pip packages every time to determine if anything changed.

Would it be possible to either
a. Bring back the hashing using the `--modifiedFilepaths flag` or
b. structure the source file query to not include source files of external dependencies?

I tried to find a query that worked for option b. but I wasn't able to. I imagine in theory something like `"rdeps(//..., //...:all-targets)` should work but that query still results in downloading all packages.

**Comment by KevinJiao** [comment]
Thanks for the response. Would the latter approach be similar to the previous form? That is, when recursively hashing dependencies, use the file contents as inputs to the hash only if the file target was specified on the commandline.

**Comment by tinder-maxwellelliott** [comment]
I reached out to the Bazel slack and it appears this kind of query is impossible, external fetches will happen.

I would gladly accept a PR that gives a list of source file targets to use, instead of doing this query

**Comment by KevinJiao** [comment]
Thanks for looking into the query with the Bazel team. I took another look at this after some more time with bazel, is it possible to replace the `kind('source file', deps(//...))` query with `kind('source file', //...:all-targets)`?  I believe this query should capture all files tracked in the repository, without requiring a fetch of all external dependencies.

The downside here is that changes in external dependencies that aren't checksummed won't be captured (I think) but morally I think this may be okay to do. I'd love to hear your thoughts on this approach.

**Comment by tinder-maxwellelliott** [comment]
I am fine with `kind('source file', //...:all-targets)`, I think that checksumming the external files is beyond this tool, id image we would pick that up from the rule implementation hash or something else

Did this work for you in your repo? I can put up a branch and try in our repo

**Comment by KevinJiao** [comment]
This worked for me, let me know how it looks on your end

**Comment by tinder-maxwellelliott** [comment]
Looking good to me!!! I can make the change

**Comment by purkhusid** [comment]
Does this change mean that changes to external deps are not detected? E.g. If I change a a Go package version?  If that is the case, then that is a huge downside IMO

**Comment by tinder-maxwellelliott** [comment]
> Does this change mean that changes to external deps are not detected? E.g. If I change a a Go package version? If that is the case, then that is a huge downside IMO

This is at the source target level, wouldn't that mean you are using unpinned deps if this were to fail?

**Comment by purkhusid** [comment]
Ok, I'll try this out on my codebase and see if we get some misses when we change 3rdparty deps. If I understand the code correctly I think we should pick up the 3rdparty changes via the rule attributes which are included in the hashes.

**Comment by tinder-maxwellelliott** [comment]
> Ok, I'll try this out on my codebase and see if we get some misses when we change 3rdparty deps. If I understand the code correctly I think we should pick up the 3rdparty changes via the rule attributes which are included in the hashes.

Really appreciate it @purkhusid , down to rollback if it breaks things but I think these changes will be surfaced somewhere else
