### ISSUE TITLE
bazel-diff hangs for projects where bazel query writes warnings to stderr

### ISSUE THREAD

**Issue by vcase** [Tinder/bazel-diff#87]
For some workspaces, the bazel query executed by bazel-diff results in a number of benign warnings being written to stderr. The code that launches bazel only reads from stdout, ignoring stderr.  As described in the below post, this will cause hangs if the process writes to stderr.

https://stackoverflow.com/a/3285479

I've created a pr to address the issue.  Of course, it needs review from a project maintainer.
https://github.com/Tinder/bazel-diff/pull/85

**Comment by tinder-maxwellelliott** [comment]
Merged it in! Thanks @vcase
