### ISSUE TITLE
Usage: The use of `//external:` in the list impacted targets

### ISSUE THREAD

**Issue by ewianda** [Tinder/bazel-diff#93]
This is an amazing tool with great potential.

My approach to use this in CI is something along the line of 

`bazel test $(cat /tmp/impacted_targets.txt)` 

However, I get 

```
Found reference to a workspace rule in a context where a build rule was expected; probably a reference to a target in that external repository, properly specified as @reponame//path/to/package:target, should have been specified by the requesting rule
```
for all `//external/` targets.

Just wondering why we have `//external` in list of impacted targets. 

Because my natural next step is to remove all the `//external` targets before invoking bazel.

**Comment by tinder-maxwellelliott** [comment]
Hello @ewianda , Thanks for the report!

I would always filter the impacted targets returned from this tool when trying do do testing. Bazel-diff is excellent at giving you all impacted targets, you will very likely need to take that list and perform queries on the targets you wish to engage with

**Comment by ewianda** [comment]
Thanks for the speedy reply.

I have been investigating 

https://github.com/bazelbuild/bazel/blob/d96e1cdbe71d117f76e55c668bb4a0f976bf0bc0/scripts/ci/ci.sh

as well. 

Seems `bazel-diff` is great replacement for these

https://github.com/bazelbuild/bazel/blob/d96e1cdbe71d117f76e55c668bb4a0f976bf0bc0/scripts/ci/ci.sh#L50-L55

and then rest of the scripts should give you what you want to build/test.

**Comment by tinder-maxwellelliott** [comment]
That looks correct, bazel-diff is giving you a large list of targets, you should perform a query with that returned list for what you want and act on that

**Comment by tinder-maxwellelliott** [comment]
Can we close this?
