### ISSUE TITLE
Generates same hashes 

### ISSUE THREAD

**Issue by Warchant** [Tinder/bazel-diff#96]
I have C/C++ project, I do this to run bazel-diff:

1. `bazel build //...` -> builds all files
2. run bazel-diff: `java -jar bazel-diff_deploy.jar generate-hashes -b .\bazel.exe -w C:\project A.txt`
3. change single .c file in a project
4. run bazel-diff: `java -jar bazel-diff_deploy.jar generate-hashes -b .\bazel.exe -w C:\project B.txt`
5. `bazel build //...`  -> this rebuilds this single .c file - bazel detected change correctly
6. run bazel-diff: `java -jar bazel-diff_deploy.jar generate-hashes -b .\bazel.exe -w C:\project C.txt`

Then all 3 files are same: {A,B,C}.txt. What do I do wrong? Why bazel-diff does not detect that configuration changed?

My goal is to find a list of labels/files that changed between 2 git commits.

**Comment by tinder-maxwellelliott** [comment]
Hello there,

The best way for me to fix this for everyone is if you could provide a small repo, then I can test my fix in there.
